export async function generateCaption({
	influencer,
	topic,
	tone = "friendly, energetic",
	niche = "general",
}) {
	try {
		if (!process.env.OPENROUTER_API_KEY) {
			throw new Error("OPENROUTER_API_KEY is missing");
		}

		const prompt = `
    You are a creative social media assistant for ${influencer}.
    Write a short (under 100 words) engaging caption for an Instagram Reel about: "${topic}".
    Tone: ${tone}. Niche: ${niche}.
    Include ~5 relevant hashtags. Keep it catchy and authentic.
    `;

		const response = await fetch(
			"https://openrouter.ai/api/v1/chat/completions",
			{
				method: "POST",
				headers: {
					Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
					"Content-Type": "application/json",
				},
				body: JSON.stringify({
					model: "meta-llama/llama-3.1-8b-instruct", // or "openai/gpt-4o-mini"
					messages: [
						{
							role: "system",
							content:
								"You write engaging, viral social media captions for Instagram Reels.",
						},
						{ role: "user", content: prompt },
					],
					temperature: 0.8,
					max_tokens: 150,
				}),
			}
		);

		if (!response.ok) {
			const errText = await response.text();
			console.error("OpenRouter error:", errText);
			throw new Error("Failed to fetch from OpenRouter API");
		}

		const data = await response.json();
		const caption = data?.choices?.[0]?.message?.content?.trim();

		if (!caption) {
			console.error(
				"Empty caption response:",
				JSON.stringify(data, null, 2)
			);
			throw new Error("No caption generated by AI");
		}

		console.log("✅ Caption generated via OpenRouter:", caption);
		return caption;
	} catch (err) {
		console.error("❌ OpenRouter caption generation failed:", err);
		return "⚠️ AI caption unavailable.";
	}
}
